import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";

const DynamicGrid = () => {
  const users = [
    {
      name: "Napogadi Selepe",
      language: "Sesotho sa Leboa",
      id: "AJK91MKRFIHAQHHG",
      bio: "Quisque maximus sodales mauris ut elementum. Maecenas quis nisi nunc.",
      version: 4.95,
    },
    {
      name: "Lesetja Theko",
      language: "Sesotho sa Leboa",
      id: "AATM20BURO1DHDAE",
      bio: "Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien. Nulla finibus massa at viverra facilisis. Morbi finibus dui sed est fringilla ornare.",
      version: 6.81,
    },
    {
      name: "Martiño Arxíz",
      language: "Galician",
      id: "CQ56N9MH3WK7H5YQ",
      bio: "Proin tempus eu risus nec mattis. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Nam rutrum sollicitudin ante tempus consequat. .",
      version: 7.13,
    },
    {
      name: "Malehumò Ledwaba",
      language: "Sesotho sa Leboa",
      id: "E4F3HGRTKQKCT1SE",
      bio: "Ut accumsan, est vel fringilla varius, purus augue blandit nisl, eu rhoncus ligula purus vel dolor. Curabitur quis commodo quam. Quisque maximus sodales mauris ut elementum. Curabitur sed condimentum felis, ut luctus eros. Curabitur ultricies id urna nec ultrices.",
      version: 6.52,
    },
    {
      name: "Musa Yasin",
      language: "Uyghur",
      id: "1AF8GIQZ1LF8QW0U",
      bio: "Phasellus tincidunt sollicitudin posuere. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros. Ut accumsan, est vel fringilla varius, purus augue blandit nisl, eu rhoncus ligula purus vel dolor.",
      version: 1.54,
    },
    {
      name: "Lajwanti Kumari",
      language: "Sindhi",
      id: "INRW3R54RAY7J9IS",
      bio: "In sed ultricies lorem. Sed eu libero maximus nunc lacinia lobortis et sit amet nisi. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      version: 9.34,
    },
    {
      name: "Maria Sammut",
      language: "Maltese",
      id: "BJRF0BWIHJ0Q12A1",
      bio: "Maecenas tempus neque ut porttitor malesuada. Curabitur ultricies id urna nec ultrices.",
      version: 6.83,
    },
    {
      name: "Rita Busuttil",
      language: "Maltese",
      id: "1QLMU6QZ7EYUNNZV",
      bio: "Phasellus tincidunt sollicitudin posuere. Quisque efficitur vel sapien ut imperdiet. Vestibulum pharetra libero et velit gravida euismod. Maecenas tempus neque ut porttitor malesuada.",
      version: 2.09,
    },
    {
      name: "Roi Fraguela",
      language: "Galician",
      id: "UAT0M2O42E9M4SFT",
      bio: "Donec congue sapien vel euismod interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue aliquam elit ut luctus. Morbi ac tellus erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      version: 1.08,
    },
    {
      name: "Matome Molamo",
      language: "Sesotho sa Leboa",
      id: "7HI0UZZLRB9N5CBI",
      bio: "Vestibulum pharetra libero et velit gravida euismod. Fusce eu ultrices elit, vel posuere neque. Duis pellentesque ultrices convallis.",
      version: 9.55,
    },
    {
      name: "Mapula Selokela",
      language: "Sesotho sa Leboa",
      id: "6ZQTOKQI6K82EE9Q",
      bio: "Duis pellentesque ultrices convallis. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Ut viverra quis eros eu tincidunt. Proin tempus eu risus nec mattis.",
      version: 5.27,
    },
    {
      name: "Noa Ervello",
      language: "Galician",
      id: "W9FR842CI16V8NU3",
      bio: "Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Suspendisse sit amet ullamcorper sem. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex.",
      version: 9.33,
    },
    {
      name: "Naseem Kakepoto",
      language: "Sindhi",
      id: "6C7HZV4WPV9C9KS6",
      bio: "Morbi ultricies consequat ligula posuere eleifend. Fusce congue aliquam elit ut luctus. . Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula.",
      version: 1.4,
    },
    {
      name: "sayama Amir",
      language: "Sindhi",
      id: "7K4IJT1X7G0EK9WC",
      bio: "Morbi ac tellus erat. Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. Maecenas quis nisi nunc. Etiam congue dignissim volutpat. Sed nec suscipit ligula.",
      version: 9.48,
    },
    {
      name: "Mariña Quintá",
      language: "Galician",
      id: "7GXC4OQYXX5JJY9F",
      bio: "Phasellus tincidunt sollicitudin posuere. Morbi ac tellus erat. Nullam ac sodales dolor, eu facilisis dui.",
      version: 8.81,
    },
    {
      name: "Memet Tursun",
      language: "Uyghur",
      id: "KSFMV2JK2D553083",
      bio: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Morbi finibus dui sed est fringilla ornare. Suspendisse sit amet ullamcorper sem.",
      version: 7.56,
    },
    {
      name: "Carmen Vella",
      language: "Maltese",
      id: "WUALBIMS4E8JS4L2",
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet sodales nunc a pulvinar. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Vestibulum pharetra libero et velit gravida euismod.",
      version: 4.55,
    },
    {
      name: "Sobia Khanam",
      language: "Sindhi",
      id: "YG1ERFWBJ7TIW35D",
      bio: "Phasellus tincidunt sollicitudin posuere. Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. Morbi ultricies consequat ligula posuere eleifend. Curabitur sed condimentum felis, ut luctus eros.",
      version: 4.59,
    },
    {
      name: "Raheela Ali",
      language: "Sindhi",
      id: "7JGX9SMLD5DE2IMG",
      bio: "Morbi finibus dui sed est fringilla ornare. Maecenas quis nisi nunc. Maecenas tempus neque ut porttitor malesuada. Curabitur ultricies id urna nec ultrices.",
      version: 4.75,
    },
    {
      name: "Rashid Rajput",
      language: "Sindhi",
      id: "UNBGUGDUATATCLS4",
      bio: "Donec congue sapien vel euismod interdum. Maecenas quis nisi nunc.",
      version: 8.51,
    },
    {
      name: "Uxía Feal",
      language: "Galician",
      id: "35ZPXUNH1M6W3ZJP",
      bio: "Vestibulum pharetra libero et velit gravida euismod. Vivamus id faucibus velit, id posuere leo.",
      version: 1.31,
    },
    {
      name: "Andrew Fenech",
      language: "Maltese",
      id: "VEYKDKL8L0R0C7GQ",
      bio: "In sed ultricies lorem. Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien. Sed laoreet posuere sapien, ut feugiat nibh gravida at.",
      version: 2.5,
    },
    {
      name: "Nicholas Micallef",
      language: "Maltese",
      id: "ZYCAI905154LSICR",
      bio: "Nam tristique feugiat est vitae mollis. Curabitur ultricies id urna nec ultrices. Morbi finibus dui sed est fringilla ornare.",
      version: 6.47,
    },
    {
      name: "Paul Borg",
      language: "Maltese",
      id: "8AD5MMJ0TD0NJ6H2",
      bio: "Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien.",
      version: 3.77,
    },
    {
      name: "Sara Saleem",
      language: "Sindhi",
      id: "5LPKMTZI7OPSJRBA",
      bio: "Maecenas tempus neque ut porttitor malesuada. Etiam congue dignissim volutpat. Proin tempus eu risus nec mattis. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Duis commodo orci ut dolor iaculis facilisis.",
      version: 5.31,
    },
    {
      name: "Xurxo Golán",
      language: "Galician",
      id: "526ZUSGXEETODHJK",
      bio: "Ut viverra quis eros eu tincidunt. Morbi finibus dui sed est fringilla ornare. Sed laoreet posuere sapien, ut feugiat nibh gravida at. Duis commodo orci ut dolor iaculis facilisis. In sed ultricies lorem.",
      version: 1.75,
    },
    {
      name: "Peter Zammit",
      language: "Maltese",
      id: "NNRT5QWNWO2WLS5V",
      bio: "Duis commodo orci ut dolor iaculis facilisis. Maecenas quis nisi nunc.",
      version: 8.23,
    },
    {
      name: "Maname Mohlare",
      language: "Sesotho sa Leboa",
      id: "KZJZ9SD0DIWTIBUC",
      bio: "Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Vestibulum pharetra libero et velit gravida euismod. Ut accumsan, est vel fringilla varius, purus augue blandit nisl, eu rhoncus ligula purus vel dolor. Sed eu libero maximus nunc lacinia lobortis et sit amet nisi.",
      version: 8.95,
    },
    {
      name: "Tshepè Mobu",
      language: "Sesotho sa Leboa",
      id: "8CH586LQR7ZCP73P",
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla finibus massa at viverra facilisis.",
      version: 7.82,
    },
    {
      name: "Monica Lohana",
      language: "Sindhi",
      id: "KP1C2WN3DN1R3Y52",
      bio: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Aenean finibus in tortor vel aliquet. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci.",
      version: 7.95,
    },
    {
      name: "Patigul Rahman",
      language: "Uyghur",
      id: "NXMNLB0SOYET1VMN",
      bio: "In sed ultricies lorem. Proin tempus eu risus nec mattis. Nam rutrum sollicitudin ante tempus consequat. Aliquam scelerisque pretium tellus, sed accumsan est ultrices id.",
      version: 2.98,
    },
    {
      name: "Joanne Scerri",
      language: "Maltese",
      id: "H8FJ2WKLGGF3K26U",
      bio: "Fusce eu ultrices elit, vel posuere neque. Nulla finibus massa at viverra facilisis. Duis commodo orci ut dolor iaculis facilisis. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula.",
      version: 8.4,
    },
    {
      name: "Ratanang Maphutha",
      language: "Sesotho sa Leboa",
      id: "EZXJTQQ2JWPB5DI3",
      bio: "Vivamus id faucibus velit, id posuere leo. Phasellus tincidunt sollicitudin posuere. Duis pellentesque ultrices convallis.",
      version: 9.17,
    },
    {
      name: "Kamil Mehmud",
      language: "Uyghur",
      id: "M24A9OMYPSX7FD16",
      bio: "Donec congue sapien vel euismod interdum. Suspendisse potenti. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Nunc aliquet sodales nunc a pulvinar. Ut viverra quis eros eu tincidunt.",
      version: 4.66,
    },
    {
      name: "Thobile Mbele",
      language: "isiZulu",
      id: "631M00M8YFFBC5NC",
      bio: "Nunc aliquet sodales nunc a pulvinar. Proin tempus eu risus nec mattis. Proin tempus eu risus nec mattis. Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus.",
      version: 8.96,
    },
    {
      name: "Kristján Kristjánsson",
      language: "Icelandic",
      id: "0WT0ZW50DNSTCHKW",
      bio: "Quisque maximus sodales mauris ut elementum. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Donec congue sapien vel euismod interdum. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Donec lobortis eleifend condimentum.",
      version: 8.82,
    },
    {
      name: "Stefán Stefánsson",
      language: "Icelandic",
      id: "1UOL8UK8BWAOSYTC",
      bio: "Suspendisse potenti. Duis luctus, lacus eu aliquet convallis, purus elit malesuada ex, vitae rutrum ipsum dui ut magna. Morbi ultricies consequat ligula posuere eleifend.",
      version: 7.87,
    },
    {
      name: "Preeti Rajdan",
      language: "Hindi",
      id: "3UN0X88Y4WYH3X8X",
      bio: "In sed ultricies lorem. Vivamus id faucibus velit, id posuere leo. Duis commodo orci ut dolor iaculis facilisis. Nam rutrum sollicitudin ante tempus consequat.",
      version: 9.17,
    },
    {
      name: "Sanjay Trivedi",
      language: "Hindi",
      id: "CPHR246457BD01KY",
      bio: "Quisque maximus sodales mauris ut elementum. Morbi ac tellus erat. Maecenas tempus neque ut porttitor malesuada. Cras dictum dolor lacinia lectus vehicula rutrum.",
      version: 8.3,
    },
    {
      name: "Smiriti Sisodiya",
      language: "Hindi",
      id: "X3KWIL5KEHTMCKOM",
      bio: "Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Morbi finibus dui sed est fringilla ornare.",
      version: 3.27,
    },
    {
      name: "Sandeep Benarjee",
      language: "Hindi",
      id: "9TS6CIE3UAIFG2IB",
      bio: "Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Sed nec suscipit ligula. Quisque efficitur vel sapien ut imperdiet. Suspendisse sit amet ullamcorper sem.",
      version: 3.86,
    },
    {
      name: "Damir Benic",
      language: "Bosnian",
      id: "QUNL9VBRHUGNOFMJ",
      bio: ". Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo.",
      version: 9.56,
    },
    {
      name: "Sigrún Kristjánsdóttir",
      language: "Icelandic",
      id: "BT1Q0NUPKHDVCFLE",
      bio: "Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Nulla finibus massa at viverra facilisis.",
      version: 6.78,
    },
    {
      name: "Basetsana Thage",
      language: "Setswana",
      id: "R9P3P2IAN7NY2X2Y",
      bio: "Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Nulla finibus massa at viverra facilisis. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula.",
      version: 3.97,
    },
    {
      name: "Rajesh Santoshi",
      language: "Hindi",
      id: "OXQTFZHZW8SVE3SY",
      bio: "Donec lobortis eleifend condimentum. Nam rutrum sollicitudin ante tempus consequat. Nullam sodales convallis mauris, sit amet lobortis magna auctor sit amet.",
      version: 8.35,
    },
    {
      name: "Margrét Magnúsdóttir",
      language: "Icelandic",
      id: "1P6VZEDGK2XUU97L",
      bio: "Sed eu libero maximus nunc lacinia lobortis et sit amet nisi. Duis pellentesque ultrices convallis. Donec lobortis eleifend condimentum.",
      version: 3.76,
    },
    {
      name: "Makhosi Ngiba",
      language: "isiZulu",
      id: "CTM3Y3TZOLC7TPDU",
      bio: "Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Suspendisse sit amet ullamcorper sem. Donec lobortis eleifend condimentum. Aenean finibus in tortor vel aliquet. Proin tempus eu risus nec mattis.",
      version: 1.18,
    },
    {
      name: "Lorato Bogosi",
      language: "Setswana",
      id: "EEZ0KS5E0RXACAIA",
      bio: "Morbi ultricies consequat ligula posuere eleifend. Nam rutrum sollicitudin ante tempus consequat. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Curabitur ultricies id urna nec ultrices.",
      version: 5.48,
    },
    {
      name: "Modisaotsile Bolokwe",
      language: "Setswana",
      id: "DN068KNEOAQ8LM19",
      bio: "Nullam ac sodales dolor, eu facilisis dui. Duis commodo orci ut dolor iaculis facilisis. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Donec congue sapien vel euismod interdum. Sed nec suscipit ligula.",
      version: 4.23,
    },
    {
      name: "Mxolisi Mhlongo",
      language: "isiZulu",
      id: "Q2HFB19RPLHIZXKH",
      bio: "Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. Maecenas tempus neque ut porttitor malesuada. . Duis commodo orci ut dolor iaculis facilisis.",
      version: 7.49,
    },
    {
      name: "Moni Sisodiya",
      language: "Hindi",
      id: "3CR7CN74GCKXWUQF",
      bio: "Vestibulum pharetra libero et velit gravida euismod. Donec congue sapien vel euismod interdum. Fusce congue aliquam elit ut luctus. Ut viverra quis eros eu tincidunt. Phasellus tincidunt sollicitudin posuere.",
      version: 4.58,
    },
    {
      name: "Anna Jónsdóttir",
      language: "Icelandic",
      id: "CKJW1XVW90VWO4Y1",
      bio: "Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien. Donec lobortis eleifend condimentum. Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien.",
      version: 5.78,
    },
    {
      name: "Darko Basic",
      language: "Bosnian",
      id: "FWT1CZQOIVRJTXRD",
      bio: "Donec congue sapien vel euismod interdum. Fusce eu ultrices elit, vel posuere neque. Duis luctus, lacus eu aliquet convallis, purus elit malesuada ex, vitae rutrum ipsum dui ut magna.",
      version: 2.27,
    },
    {
      name: "Kedibonye Magogwe",
      language: "Setswana",
      id: "PCT0HLRPZLDSSDU1",
      bio: "Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Quisque maximus sodales mauris ut elementum.",
      version: 5.57,
    },
    {
      name: "Nobuhle Xaba",
      language: "isiZulu",
      id: "5K1K8V1OUUFKQ2UV",
      bio: "Maecenas non arcu nulla. Morbi ac tellus erat.",
      version: 1.18,
    },
    {
      name: "Monty Dubey",
      language: "Hindi",
      id: "B7SF955NFGAEBRXU",
      bio: "Maecenas quis nisi nunc. Maecenas tempus neque ut porttitor malesuada. Morbi ultricies consequat ligula posuere eleifend. Ut accumsan, est vel fringilla varius, purus augue blandit nisl, eu rhoncus ligula purus vel dolor.",
      version: 6.69,
    },
    {
      name: "Richa Choukse",
      language: "Hindi",
      id: "BADWLBP8CNJNBEC8",
      bio: "Nunc tincidunt laoreet laoreet. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Curabitur quis commodo quam. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci.",
      version: 7.8,
    },
    {
      name: "Dzenan Imamovic",
      language: "Bosnian",
      id: "FVAHD0OY99X9DIRW",
      bio: "Nam tristique feugiat est vitae mollis. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Nullam ac sodales dolor, eu facilisis dui. Morbi finibus dui sed est fringilla ornare. Quisque efficitur vel sapien ut imperdiet.",
      version: 1.64,
    },
    {
      name: "Amol Bhatnagar",
      language: "Hindi",
      id: "3HPSETKL9VOW2WTL",
      bio: "Vestibulum pharetra libero et velit gravida euismod. Nam semper gravida nunc, sit amet elementum ipsum.",
      version: 3.28,
    },
    {
      name: "Ingibjörg Ólafsdóttir",
      language: "Icelandic",
      id: "9BXLMMM1PQOZRHCR",
      bio: "Maecenas non arcu nulla. Sed nec suscipit ligula. Fusce congue aliquam elit ut luctus.",
      version: 9.59,
    },
    {
      name: "Shweta Chourasia",
      language: "Hindi",
      id: "9GAO62FXPQMUTTLJ",
      bio: "Duis luctus, lacus eu aliquet convallis, purus elit malesuada ex, vitae rutrum ipsum dui ut magna. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Quisque maximus sodales mauris ut elementum. Sed eu libero maximus nunc lacinia lobortis et sit amet nisi.",
      version: 5.84,
    },
    {
      name: "Ayanda Ndimande",
      language: "isiZulu",
      id: "VPK9MQRKX2L847HQ",
      bio: "Duis commodo orci ut dolor iaculis facilisis. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus.",
      version: 2.89,
    },
    {
      name: "Sigurjón Guðmundsson",
      language: "Icelandic",
      id: "IAYT285H2U8JU94F",
      bio: "Sed eu libero maximus nunc lacinia lobortis et sit amet nisi. Ut viverra quis eros eu tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et.",
      version: 4.85,
    },
    {
      name: "Jóhannes Jóhannsson",
      language: "Icelandic",
      id: "J2RAROEJGKMR72I8",
      bio: "Duis pellentesque ultrices convallis. Nulla finibus massa at viverra facilisis. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo.",
      version: 4.83,
    },
    {
      name: "Neo Dikgaka",
      language: "Setswana",
      id: "OQRF6Y37N20JILOC",
      bio: "Nam tristique feugiat est vitae mollis. Sed nec suscipit ligula. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Duis pellentesque ultrices convallis. Maecenas quis nisi nunc.",
      version: 1.07,
    },
    {
      name: "Sanja Jankovic",
      language: "Bosnian",
      id: "HD94EKIPA6WAL05C",
      bio: "Phasellus tincidunt sollicitudin posuere. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Donec congue sapien vel euismod interdum. Nullam ac sodales dolor, eu facilisis dui.",
      version: 1.06,
    },
    {
      name: "Mogorosi Bakwena",
      language: "Setswana",
      id: "FTZM8YDJJUH1OEM7",
      bio: "Vestibulum pharetra libero et velit gravida euismod. Suspendisse sit amet ullamcorper sem.",
      version: 6.03,
    },
    {
      name: "Ronak Gupta",
      language: "Hindi",
      id: "ZYPDGK8UDYJPTRKN",
      bio: "Sed laoreet posuere sapien, ut feugiat nibh gravida at. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. In sed ultricies lorem. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna.",
      version: 7.18,
    },
    {
      name: "Ditiro Kgosi",
      language: "Setswana",
      id: "67C5ET66U59WYJ6K",
      bio: "Fusce congue aliquam elit ut luctus. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Cras dictum dolor lacinia lectus vehicula rutrum. Etiam congue dignissim volutpat.",
      version: 4.56,
    },
    {
      name: "Jelena Maric",
      language: "Bosnian",
      id: "JTW9DH3B9QGB39JY",
      bio: "Vestibulum pharetra libero et velit gravida euismod. Etiam malesuada blandit erat, nec ultricies leo maximus sed.",
      version: 3.39,
    },
    {
      name: "Esha Sastry",
      language: "Hindi",
      id: "4OJULHY03Z6XTRMW",
      bio: "Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Nullam ac sodales dolor, eu facilisis dui.",
      version: 5.1,
    },
    {
      name: "Chetana Hegde",
      language: "Hindi",
      id: "J9GS1RODDZL325LK",
      bio: "Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Nulla finibus massa at viverra facilisis. Nam tristique feugiat est vitae mollis. Phasellus tincidunt sollicitudin posuere.",
      version: 9.99,
    },
    {
      name: "Rahul Shukla",
      language: "Hindi",
      id: "2ANVMAVG6YX2VT6N",
      bio: "Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula.",
      version: 1.72,
    },
    {
      name: "Samra Delic",
      language: "Bosnian",
      id: "BXJWNTJ2TDID61PJ",
      bio: "Donec pellentesque ultrices mi, non consectetur eros luctus non. Sed nec suscipit ligula.",
      version: 2.5,
    },
    {
      name: "Mohan Pandey",
      language: "Hindi",
      id: "XAHKVLM3I1WSPNIW",
      bio: "Maecenas quis nisi nunc. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros. Morbi ac tellus erat.",
      version: 8.1,
    },
    {
      name: "Haris Osmanovic",
      language: "Bosnian",
      id: "ZDXF5KESMW9XF2TJ",
      bio: "Nam rutrum sollicitudin ante tempus consequat. Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien.",
      version: 9.41,
    },
    {
      name: "Kenosi Kwenaemang",
      language: "Setswana",
      id: "DX2IYTQ9IMY75W08",
      bio: "Sed laoreet posuere sapien, ut feugiat nibh gravida at. Donec lobortis eleifend condimentum.",
      version: 9.01,
    },
    {
      name: "Nontobeko Nzimande",
      language: "isiZulu",
      id: "Y9C4HQHTOP74DFZT",
      bio: "Nullam sodales convallis mauris, sit amet lobortis magna auctor sit amet. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus.",
      version: 4.77,
    },
    {
      name: "Sanjay Puranik",
      language: "Hindi",
      id: "WF2WP6S0HX8GR8GZ",
      bio: "Ut viverra quis eros eu tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Nam semper gravida nunc, sit amet elementum ipsum.",
      version: 3.37,
    },
    {
      name: "Sethunya Mpšwe",
      language: "Setswana",
      id: "85MVUXVQ5H5HPA4F",
      bio: "Quisque maximus sodales mauris ut elementum. Duis commodo orci ut dolor iaculis facilisis. Sed eu libero maximus nunc lacinia lobortis et sit amet nisi.",
      version: 1.75,
    },
    {
      name: "Dileep Chaturvedi",
      language: "Hindi",
      id: "O95BY1KDMCEYQRFH",
      bio: "Phasellus tincidunt sollicitudin posuere. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Vivamus id faucibus velit, id posuere leo. Nullam ac sodales dolor, eu facilisis dui. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo.",
      version: 4.94,
    },
    {
      name: "Adnan Spahic",
      language: "Bosnian",
      id: "97IIDMHAJMBPI4ON",
      bio: "Duis commodo orci ut dolor iaculis facilisis. Vivamus id faucibus velit, id posuere leo.",
      version: 9.1,
    },
    {
      name: "Madhur Jain",
      language: "Hindi",
      id: "FM300CZ0VU9LTNTE",
      bio: "Fusce eu ultrices elit, vel posuere neque. Donec congue sapien vel euismod interdum. Vivamus id faucibus velit, id posuere leo. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et.",
      version: 4.99,
    },
    {
      name: "Nayan Mittal",
      language: "Hindi",
      id: "S879KFFIHDNK8GSE",
      bio: "Suspendisse sit amet ullamcorper sem. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Duis commodo orci ut dolor iaculis facilisis.",
      version: 3.99,
    },
    {
      name: "Kabelo Morwe",
      language: "Setswana",
      id: "JJDPB2983QRVATD3",
      bio: "Nullam ac sodales dolor, eu facilisis dui. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. . Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Curabitur ultricies id urna nec ultrices.",
      version: 8.86,
    },
    {
      name: "Einar Einarsson",
      language: "Icelandic",
      id: "ZWMFEUEBNYTW2WPB",
      bio: "Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien. Duis pellentesque ultrices convallis. Nullam sodales convallis mauris, sit amet lobortis magna auctor sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Donec congue sapien vel euismod interdum.",
      version: 9.05,
    },
    {
      name: "Luka Lovren",
      language: "Bosnian",
      id: "9S4SGEQWBKMRISYZ",
      bio: "Maecenas tempus neque ut porttitor malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis commodo quam. Nam rutrum sollicitudin ante tempus consequat.",
      version: 5.22,
    },
    {
      name: "Sigríður Einarsdóttir",
      language: "Icelandic",
      id: "4IJVD6OE3C7IX3ZG",
      bio: "Aenean finibus in tortor vel aliquet. Nam tristique feugiat est vitae mollis.",
      version: 6.63,
    },
    {
      name: "Sonu Jain",
      language: "Hindi",
      id: "0OIB5SU9JB2PBJDV",
      bio: "Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Curabitur ultricies id urna nec ultrices.",
      version: 9.66,
    },
    {
      name: "Boitumelo Ngwako",
      language: "Setswana",
      id: "INZITSS95L9V52JE",
      bio: "Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros. Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Nam tristique feugiat est vitae mollis. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. In sed ultricies lorem.",
      version: 9.07,
    },
    {
      name: "Bhupesh Menon",
      language: "Hindi",
      id: "0CEPNRDV98KT3ORP",
      bio: "Maecenas tempus neque ut porttitor malesuada. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Maecenas quis nisi nunc.",
      version: 2.69,
    },
  ];

  return (
    <View>
      <Text style={{fontSize:26, textAlign: 'center', marginTop:10,}}> Make Dynamic Grid</Text>

    <ScrollView style={{backgroundColor:'skyblue'}}> 
    <Text style={{fontSize:26, textAlign: 'center', marginTop:10, fontWeight: 'bold'}}> Name of Authors : </Text>

      <View
        style={{
          flex: 1,
          flexDirection: "row",
          flexWrap: "wrap",
        }}
      >
        {users.map((item) => (
          <Text style={style.box}> {item.name} </Text>
        ))}
      </View>
      </ScrollView>
    </View>
  );
};

const style = StyleSheet.create({
  box: {
    width: 100,
    height: 80,
    backgroundColor: "violet",
    textAlign: "center",
    textAlignVertical: "center",
    margin: 8,
  },
});

export default DynamicGrid;
